"""Fixed models with relationships and validation

Revision ID: ea0ee85485f5
Revises: 8a3a4c9e0919
Create Date: 2025-06-21 17:18:21.766320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0ee85485f5'
down_revision = '8a3a4c9e0919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appearances', sa.Column('guest_id', sa.Integer(), nullable=False))
    op.add_column('appearances', sa.Column('episode_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_appearances_episode_id_episodes'), 'appearances', 'episodes', ['episode_id'], ['id'])
    op.create_foreign_key(op.f('fk_appearances_guest_id_guests'), 'appearances', 'guests', ['guest_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_appearances_guest_id_guests'), 'appearances', type_='foreignkey')
    op.drop_constraint(op.f('fk_appearances_episode_id_episodes'), 'appearances', type_='foreignkey')
    op.drop_column('appearances', 'episode_id')
    op.drop_column('appearances', 'guest_id')
    # ### end Alembic commands ###
